---
title: "Análise da Base RAIS"
description: |
  Esse projeto tem como objetivo analisar os salários da base da RAIS. Projeto feito na Semana Data
  Science na Prática da Curso R 
author:
  - name: Rafael Rocha
date: 2021-12-06
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Nessa análise estamos interessados em responder a seguinte pergunta:

"Quanto ganha um cientista de dados no Brasil?"

Para isso vamos utilizar a base da RAIS anonimizada.

# Acessando os dados da RAIS

Vamos utilizar o datalake da [iniciativa Base dos Dados](https://basedosdados.org/).


```{r message=FALSE, warning=FALSE}
library("bigrquery")
library("dplyr")
```

O código abaixo carrega as primeiras 5 linhas da tabela de microdados

```{r, cache=TRUE}
bigrquery::bq_auth("rochaunit02@gmail.com")

conexao <- dbConnect(
  bigquery(),
  project = "basedosdados",
  dataset = "br_me_rais",
  billing = "cursor-cienciadedados"
)

primeiras_cinco_linhas <- collect(head(select(tbl(conexao, "microdados_vinculos"), everything()),5))

knitr::kable(primeiras_cinco_linhas)
```

